package:
  name: panda3d-rp-kitsunetsuki
  version: "1.3"

source:
  - git_url: https://github.com/tobspr/RenderPipeline
    patches:
      - rp.patch
      - rp-setup.patch
      - noflag.patch
      - k_shading_models.patch
      - lights.patch

build:
  number: 0
  string: 1551096942

requirements:
  build:
    - python
    - panda3d-kitsunetsuki >=1.10.1
    - m2-gcc-libs # [win]
    - m2-patch # [win]
    - msinttypes # [win]
  run:
    - python
    - panda3d-kitsunetsuki >=1.10.1
    - pyqt

about:
  home: http://www.panda3d.org/
  license: BSD
