package:
  name: panda3d-rp-kitsunetsuki
  version: "1.3"

source:
  - git_url: https://github.com/tobspr/RenderPipeline
    git_rev: 8e0212d88a138de59f08fe9d6dce148227cf8216
    patches:
      - rp.patch
      - rp-setup.patch
      - noflag.patch
      - dte.patch

build:
  number: 0
  string: 1586120650

requirements:
  build:
    - python
    - panda3d-kitsunetsuki >=1.10.2
    - m2-gcc-libs # [win]
    - m2-patch # [win]
    - msinttypes # [win]
  run:
    - python
    - panda3d-kitsunetsuki >=1.10.2
    - pyqt

about:
  home: http://www.panda3d.org/
  license: BSD
