package:
  name: panda3d-kitsunetsuki
  version: "1.10.2"

source:
  - git_url: https://github.com/panda3d/panda3d.git
    git_rev: v1.10.2
    folder: .
    patches:
      - prefix-110.patch # [win]
      - nopy.patch # [win]
      - bullet.patch
      - icon.patch # [unix]
      - is_nan.patch
      - egg1.patch
      - egg2.patch
      - egg3.patch

  - url: https://www.panda3d.org/download/panda3d-1.10.2/panda3d-1.10.2-tools-win32.zip # [win32]
    md5: 6e46e04c9cad0e6dfa3da225790f1923 # [win32]

  - url: https://www.panda3d.org/download/panda3d-1.10.2/panda3d-1.10.2-tools-win64.zip # [win64]
    md5: 46c2c10185010da9d4e9049e699b4735 # [win64]

build:
  number: 0
  string: 1556606416

requirements:
  build:
    - python
    - cmake
    - bullet ==2.83
    - pillow # [unix]
    - m2-gcc-libs # [win]
    - m2-patch # [win]
    - msinttypes # [win]
    - 7za # [win]
  run:
    - python

about:
  home: http://www.panda3d.org/
  license: BSD
