package:
  name: panda3d-kitsunetsuki
  version: "1.10.4.1"

source:
  - git_url: https://github.com/panda3d/panda3d.git
    git_rev: v1.10.4.1
    folder: .
    patches:
      - prefix-110.patch # [win]
      - nopy.patch # [win]
      - bullet.patch
      - openssl.patch
      - egg1.patch
      - egg2.patch
      - egg3.patch
      - rp_light.patch

  - url: https://www.panda3d.org/download/panda3d-1.10.4.1/panda3d-1.10.4.1-tools-win32.zip # [win32]
    md5: 03dc7f4d16f03b221b4a3752f348c1fa # [win32]

  - url: https://www.panda3d.org/download/panda3d-1.10.4.1/panda3d-1.10.4.1-tools-win64.zip # [win64]
    md5: ba4c7f881caecd7493d0c591090e1bf8 # [win64]

build:
  number: 0
  string: 1574944853

requirements:
  build:
    - python
    - cmake
    - bullet ==2.83
    - pillow # [unix]
    - m2-gcc-libs # [win]
    - m2-patch # [win]
    - msinttypes # [win]
    - 7za # [win]
  run:
    - python

about:
  home: http://www.panda3d.org/
  license: BSD
