package:
  name: panda3d-kitsunetsuki
  version: "1.10.2"

source:
  - git_url: https://github.com/panda3d/panda3d.git
    git_rev: v1.10.2
    folder: .
    patches:
      - prefix-110.patch # [win]
      - nopy.patch # [win]
      - bullet.patch
      - icon.patch # [unix]
      - is_nan.patch
      - egg1.patch
      - egg2.patch
      - egg3.patch

  - url: http://rdb.name/thirdparty-vc14.7z # [win32]
    folder: thirdparty # [win32]
    md5: 2a1c29cd5e081f81da0afe90a70a9695 # [win32]

  - url: http://rdb.name/thirdparty-vc14-x64.7z # [win64]
    folder: thirdparty # [win64]
    md5: 34575b4345e81112e25033bbb4c9c298 # [win64]

build:
  number: 0
  string: 1554714236

requirements:
  build:
    - python
    - cmake
    - bullet ==2.83
    - pillow # [unix]
    - m2-gcc-libs # [win]
    - m2-patch # [win]
    - msinttypes # [win]
    - 7za # [win]
  run:
    - python

about:
  home: http://www.panda3d.org/
  license: BSD
