package:
  name: kitsunetsuki-runtime-rp
  version: "0.4"

source:
  path: .

build:
  number: 0
  string: 1554714236

requirements:
  build:
    - panda3d-rp-kitsunetsuki >=1.3

about:
  home: https://kitsune.one/
  license: BSD
